import { Router, type IRouter } from "express";
import healthRouter from "./health";
import socialRouter from "./social";
import authRouter from "./auth";
import forumRouter from "./forum";
import youtubeRouter from "./youtube";
import blackjackRouter from "./blackjack";
import flappyRouter from "./flappy";
import ranksRouter from "./ranks";
import dmsRouter from "./dms";
import pollsRouter from "./polls";
import musicRouter from "./music";
import userpagesRouter from "./userpages";
import cafeRouter from "./cafe";
import chessRouter from "./chess";
import siteSettingsRouter from "./site-settings";
import ipAdminRouter from "./ip-admin";
import newsRouter from "./news";
import adminBackupRouter from "./admin-backup";
import cafeRoomsRouter from "./cafe-rooms";
import cafeObjectsRouter from "./cafe-objects";
import diagnosticsRouter from "./diagnostics";

const router: IRouter = Router();

router.use(healthRouter);
router.use(authRouter);
router.use(socialRouter);
router.use(forumRouter);
router.use(youtubeRouter);
router.use(blackjackRouter);
router.use(flappyRouter);
router.use(ranksRouter);
router.use(dmsRouter);
router.use(pollsRouter);
router.use(musicRouter);
router.use(userpagesRouter);
router.use(cafeRouter);
router.use(chessRouter);
router.use(siteSettingsRouter);
router.use(ipAdminRouter);
router.use(newsRouter);
router.use(cafeRoomsRouter);
router.use(cafeObjectsRouter);
router.use(diagnosticsRouter);
router.use(adminBackupRouter);

export default router;
