// This file is auto-generated by mockupPreviewPlugin.ts.
type ModuleMap = Record<string, () => Promise<Record<string, unknown>>>;
export const modules: ModuleMap = {
  "./components/mockups/wiki-cleanup/Cleaner.tsx": () => import("../components/mockups/wiki-cleanup/Cleaner.tsx"),
  "./components/mockups/wiki-cleanup/Current.tsx": () => import("../components/mockups/wiki-cleanup/Current.tsx"),
  "./components/mockups/planner-refresh/Current.tsx": () => import("../components/mockups/planner-refresh/Current.tsx"),
  "./components/mockups/planner-refresh/PlannerRefresh.tsx": () => import("../components/mockups/planner-refresh/PlannerRefresh.tsx")
};
