import type { WindowType } from "../store";

export const FEATURE_CATALOG: { id: WindowType; name: string; category: string }[] = [
  { id: "planner", name: "Planner", category: "Info" },
  { id: "news", name: "Site News", category: "Info" },
  { id: "sharedphotos", name: "Photo Gallery", category: "Info" },
  { id: "userlist", name: "Users", category: "Info" },
  { id: "visits", name: "Visitor Counter", category: "Info" },
  { id: "guestbook", name: "Guestbook", category: "Info" },
  { id: "chess", name: "Chess", category: "Games" },
  { id: "blackjack", name: "Blackjack", category: "Games" },
  { id: "flappy", name: "Flappy Bird", category: "Games" },
  { id: "geometry", name: "Geometry Dash", category: "Games" },
  { id: "poker", name: "Poker", category: "Games" },
  { id: "eaglercraft", name: "Eaglercraft", category: "Games" },
  { id: "mypage", name: "My Page", category: "Social" },
  { id: "forum", name: "Forum", category: "Social" },
  { id: "chat", name: "Chatbox", category: "Social" },
  { id: "dms", name: "Direct Messages", category: "Social" },
  { id: "youtube", name: "Synced YouTube", category: "Social" },
  { id: "cafe", name: "Cafe", category: "Social" },
  { id: "browser", name: "Web Browser", category: "Social" },
  { id: "polls", name: "Polls", category: "Social" },
  { id: "music", name: "Music Player", category: "Social" },
  { id: "personalplaylists", name: "My Playlists", category: "Social" },
  { id: "drawing", name: "Drawing Pad", category: "Social" },
  { id: "link", name: "Link Shortcut", category: "Tools" },
  { id: "text", name: "Text Note", category: "Tools" },
];
